substitutions:
  device_name:               Kitchen Fan
  device_id:                 kitchen_fan

esphome:
  name:                      ${device_id}
  platform:                  ESP8266
  board:                     esp01_1m
  comment:                   "вытяжка на кухне"

wifi:
  ssid:                      !secret wifi_ssid
  password:                  !secret wifi_password
  fast_connect:              true

api:
  password:                  !secret api_password

ota:
  password:                  !secret ota_password
  safe_mode:                 true

mqtt:
    broker:                  !secret mqtt_broker
    username:                !secret mqtt_username
    password:                !secret mqtt_password
    on_message:
      - topic:               "/kitchen/fan"
        payload:             "1"
        then:
            switch.turn_on:  "${device_id}_switch"
      - topic:               "/kitchen/fan"
        payload:             "0"
        then:
            switch.turn_off: "${device_id}_switch"
      - topic:               "/kitchen/fan"
        payload:             "x"
        then:
            switch.toggle:   "${device_id}_switch"

    topic_prefix:            /kitchen/fan
    birth_message:
        topic:               /info/fan/status
        payload:             online
        qos:                 0
        retain:              true
    will_message:
        topic:               /info/fan/status
        payload:             offline
        qos:                 0
        retain:              true
    shutdown_message:
        topic:               /info/fan/status
        payload:             offline
        qos:                 0
        retain:              true
    log_topic:
        topic:               /info/fan/error
        qos:                 0
        retain:              true

status_led:
  pin:
    number:                  GPIO1
    inverted:                true

web_server:
  port:                      80
  auth:
    username:                admin
    password:                !secret web_server_password

logger:
  baud_rate: 0
  level: ERROR

switch:
  - platform:                restart
    name:                    "${device_name} restart"
  - platform:                gpio
    pin:                     GPIO2
    name:                    "${device_name} switch"
    id:                      "${device_id}_switch"
    icon:                    "mdi:fan"
    state_topic:             /info/fan
    command_topic:           /ctl/fan

output:
  - platform:                gpio
    pin:                     GPIO2
    id:                      "${device_id}_output"

sensor:
  - platform:                wifi_signal
    name:                    ${device_name} wifi signal
    state_topic:             /info/fan/wifi
    update_interval:         60s
  - platform:                uptime
    name:                    ${device_name} uptime
    state_topic:             /info/fan/uptime
    update_interval:         60s
