esphome:
  name:          sonoff_plug_s26_0
  platform:      ESP8266
  board:         esp8285
  #  arduino_version: 2.4.2

wifi:
  ssid:          !secret wifi_ssid
  password:      !secret wifi_password
  fast_connect:  true

api:
  password:      !secret s26_api_password

logger:


binary_sensor:
- platform:      gpio
  pin:
    number:      GPIO0
    mode:        INPUT_PULLUP
    inverted:    True
  name:          "Sonoff S26 Button"
  id:            "sonoff_s26_button"
  on_press:
    - switch.toggle: relay
- platform:      status
  name:          "Sonoff S26 Status"


switch:
- platform:      gpio
  name:          "Sonoff S26 Relay"
  pin:           GPIO12
  id:            relay
  icon:          "mdi:power-socket-de"
  restore_mode:  RESTORE_DEFAULT_ON

output:
- platform:      esp8266_pwm
  id:            s26_green_led
  pin:           GPIO13
  inverted:      True

light:
- platform:      monochromatic
  name:          "Sonoff S26 Green LED"
  output:        s26_green_led
  restore_mode:  ALWAYS_ON
