substitutions:
  device_name:  Sonoff S26 plug
  device_id:    sonoff_plug0

esphome:
  name:         ${device_id}
  platform:     ESP8266
  board:        esp8285
  #  arduino_version: 2.4.2

wifi:
  ssid:         !secret wifi_ssid
  password:     !secret wifi_password
  fast_connect: true

api:
  password:     !secret s26_api_password

logger:

binary_sensor:
  - platform:   gpio
    pin:
      number:   GPIO0
      mode:     INPUT_PULLUP
      inverted: True
    name:       "${device_name} button"
    id:         ${device_id}_button
    on_press:
      - switch.toggle: ${device_id}_relay
  - platform:   status
    name:       "${device_name} Status"


switch:
- platform:     gpio
  name:         "${device_name} relay"
  pin:          GPIO12
  id:           ${device_id}_relay
  icon:         "mdi:power-socket-de"
  restore_mode: RESTORE_DEFAULT_ON

output:
- platform:     esp8266_pwm
  id:           ${device_id}_green_led
  pin:          GPIO13
  inverted:     true

light:
- platform:     monochromatic
  name:         "${device_name} green led"
  output:       ${device_id}_green_led
  restore_mode: ALWAYS_ON
